alter table CUBAPLATFORMSAMPLER_SESSION alter column DISCRIPTION rename to DISCRIPTION__U77359 ^
alter table CUBAPLATFORMSAMPLER_SESSION add column DESCRIPTION varchar(2000) ^
update CUBAPLATFORMSAMPLER_SESSION set DESCRIPTION = '' where DESCRIPTION is null ;
alter table CUBAPLATFORMSAMPLER_SESSION alter column DESCRIPTION set not null ;
