-- begin CUBAPLATFORMSAMPLER_SESSION
alter table CUBAPLATFORMSAMPLER_SESSION add constraint FK_CUBAPLATFORMSAMPLER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBAPLATFORMSAMPLER_SPEAKER(ID)^
create index IDX_CUBAPLATFORMSAMPLER_SESSION_ON_SPEAKER on CUBAPLATFORMSAMPLER_SESSION (SPEAKER_ID)^
-- end CUBAPLATFORMSAMPLER_SESSION
